---
# Source: godemo41/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: godemo41-godemo41
  namespace: myapps
  labels:
    draft: draft-app
    chart: "godemo41-0.0.6"
spec:
  selector:
    matchLabels:
      app: godemo41-godemo41
  replicas: 1
  template:
    metadata:
      labels:
        draft: draft-app
        app: godemo41-godemo41
    spec:
      containers:
      - name: godemo41
        image: "gcr.io/jstrachan-multicluster/godemo41:0.0.6"
        imagePullPolicy: IfNotPresent
        env:
        envFrom:
          null
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds:
