---
# Source: godemo41/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: godemo41
  namespace: myapps
  labels:
    chart: "godemo41-0.0.6"
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: godemo41-godemo41
